APP_NAME: Geosite Server
APP_VERSION: 1.0

DB_NAME: geosite
DB_USER: geosite
DB_PASS: geosite

VENV_NAME: geosite
VENV_PATH: /home/vagrant/.venvs/geosite

STATIC_SRC:
  geositeserver: /home/vagrant/geosite-server.git/geositeserver/static/geositeserver

STATIC_DEST: /var/www
STATIC_ROOT: /var/www/static
WWW_ROOT: /var/www

PRJ_PARENT_PATH: /home/vagrant
PRJ_REPO_NAME: geosite-server.git

PRJ_REPO_PATH_MAIN:  /home/vagrant/geosite-server.git
PRJ_DJ_NAME: geositeserver

REQS:
  - "~/geosite-server.git/requirements.txt"

JENKS: "git+https://github.com/perrygeo/jenks.git#egg=jenks"

#STATIC_DEV_DEPS:
#  - { name: bower, version: 1.7.7 }
#  - { name: gulp, version: 3.9.1 }
#  - { name: del, version: 2.2.0 }
#  - { name: path, version: 0.12.7 }
#  - { name: jshint, version: 2.9.1 }
#  - { name: gulp-concat, version: 2.6.0 }
#  - { name: gulp-jshint, version: 2.0.0 }
#  - { name: gulp-minify, version: 0.0.5 }
#  - { name: gulp-uglify, version: 1.5.2 }
#  - { name: gulp-rename, version: 1.2.2 }
#  - { name: gulp-less, version: 3.0.5 }

COMMON_EDITABLE_PACKAGES:  # For role "common_editable"
  - name: geosite-server
    parent: /home/vagrant
    path: geosite-server.git
  - name: geosite-framework-django
    parent: /home/vagrant
    path: geosite-framework-django.git


PATH_PG_HBA: "/etc/postgresql/9.3/main/pg_hba.conf"
PATH_PG_CONF: "/etc/postgresql/9.3/main/postgresql.conf"

DJANGO_APPS:
  - "geositeserver"
  - "wfppresencedjango"
  - "lsibdjango"
  - "gauldjango"

DJANGO_FIXTURES:
  - "geositeserver/fixtures/maps.yml"

SUPERUSER_USERNAME: admin
SUPERUSER_EMAIL: admin@example.com
