---

- name: "Update NGINX / sites-available/default"
  become: yes
  become_user: root
  action: template src=templates/nginx.sites-available.default.j2 dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: Create WWW Root
  become: yes
  become_user: root
  file: "path={{ WWW_ROOT }} state=directory owner=root"

- name: Create Static Destination
  become: yes
  become_user: root
  file: "path={{ STATIC_DEST }} state=directory owner=root"

- name: Collect Static
  become: yes
  become_user: root
  shell: "{{ VENV_PATH }}/bin/python manage.py collectstatic --noinput -i gulpfile.js -i package.json -i temp -i node_modules > /dev/null 2>&1"
  args:
    chdir: "{{ PRJ_REPO_PATH_MAIN }}"
